apiVersion: v1
kind: Service
metadata:
  name: knode-service
  labels:
    app: knode
spec:
  selector:
    app: knode  # 해당 label을 가진 Pod들을 선택
  ports:
    - protocol: TCP
      port: 80   # 외부에서 접근할 포트
      targetPort: 8080  # 실제 Pod에서 열려 있는 포트
      nodePort: 30001
  type: NodePort # 클러스터 외부에서 접근할 수 있도록 설정
