apiVersion: v1
kind: Service
metadata:
  name: knode-service
  labels:
    ap: knode
spec:
  selector:
    app: knode  # 해당 label을 가진 Pod들을 선택
  ports:
    - protocol: TCP
      port: 80         # 외부에서 접근할 포트
      targetPort: 80    # 실제 Pod에서 열려 있는 포트
  type: LoadBalancer   # MetalLB에서 외부 IP를 할당해 로드밸런서 역할을 하도록 설정
