---
- hosts: kubernetes
  user: master

  tasks:
    - name: deploy knode on kubernetes
      command: kubectl apply -f /master/sources/replication/deployment.yaml

    - name: create service for knode
      command: kubectl apply -f /master/sources/replication/knode-service.yaml

    - name: update deployment with new pods if image updated in docker hub
      command: kubectl rollout restart deployment.apps/knode
